kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: "https://github.com/vrutkovs/mirror-mirror"
  name: mirror-mirror
  namespace: mirror-mirror
  labels:
    app: mirror-mirror
    app.kubernetes.io/component: mirror-mirror
    app.kubernetes.io/instance: mirror-mirror
    app.kubernetes.io/name: mirror-mirror
    app.kubernetes.io/part-of: mirror-mirror-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.12-ubi8
spec:
  lookupPolicy:
    local: false
