kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ""
    app.openshift.io/vcs-uri: "https://github.com/vrutkovs/mirror-mirror"
  name: mirror-bot
  namespace: mirror-mirror
  labels:
    app: mirror-mirror
    app.kubernetes.io/component: mirror-mirror
    app.kubernetes.io/instance: mirror-mirror
    app.kubernetes.io/name: mirror-mirror
    app.kubernetes.io/part-of: mirror-mirror-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.12-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: "mirror-mirror:bot"
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: "https://github.com/vrutkovs/mirror-mirror"
    contextDir: /src/bot
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: mirror-mirror-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: mirror-mirror-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
