kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hg-cache
  namespace: mirror-mirror
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: gp3-csi
  volumeMode: Filesystem
